{% set name = "scico" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scico-{{ version }}.tar.gz
  sha256: 35f3a1af77f31a9e74fa9846fb67c8c15c04076c3503fa37c36c04d245352ff7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - typing_extensions
    - numpy >=1.20.0
    - scipy >=1.6.0
    - imageio >=2.17
    - tifffile
    - matplotlib-base
    - jax >=0.4.13,<=0.4.35
    - flax >=0.8.0,<=0.10.0
    - chex >=0.1.7
    - optax >=0.1.5
    - orbax-checkpoint >=0.5.0
    - pyabel >=0.9.0
    - xdesign >=0.5.5
    - astra-toolbox
    - svmbir >=0.3.3
    - ray-dashboard >=2.5.0
    - ray-train >=2.5.0
    - ray-tune >=2.5.0
    - hyperopt

test:
  imports:
    - scico
    - scico.data
    - scico.flax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lanl/scico
  summary: 'Scientific Computational Imaging COde: A Python package for scientific imaging problems'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bwohlberg
